### ISSUE TITLE
Laravel ^7.0 Support

### ISSUE THREAD

**Issue by ericksuryadinata** [ibnujakaria/file-manager#17]
I need it for laravel ^7.0 support

**Comment by ibnujakaria** [comment]
I'm open for pull request anyway...

**Comment by ibnujakaria** [comment]
Hello @ericksuryadinata 

Thanks for pointing this out.

You can now install the [v2.0.1](https://github.com/ibnujakaria/file-manager/releases/tag/v2.0.1) version on a Laravel 7 project.
